name: Issue
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  Output:
    runs-on: ubuntu-latest
    steps:
      - name: Outputing event details
        run: echo "${{ toJSON(github.event) }}"